# pull the official base image
FROM node:18-alpine

RUN mkdir -p /app

# set working direction
WORKDIR /app

# install application dependencies
COPY package.json ./
COPY yarn.lock ./

RUN apk add --update python3 make g++ && rm -rf /var/cache/apk/*
RUN yarn install

COPY . ./

EXPOSE 3000
ARG ENV

RUN if [ "$ENV" = "production" ] ; then yarn build ; else echo "Skipping build" ; fi

# for prod use this
# CMD ["npx", "serve", "-s", "build"]

# For dev
CMD ["yarn", "run", "dev"]
